### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by yomena** [yomena/kwikr#2]

**Comment by yomena** [comment]
- [ ] Optimize file structure
- [ ] Add more fields to settings.json
- [ ] Add FTP support
- [ ] Write documentation
- [ ] Create icon
- [ ] Build a project website
- [ ] Add tasks to gulp (autoprefix, ...)
- [ ] Simplify installation
- [ ] Add framework options (SemanticUI, Foundation, ...)
- [ ] Optimize example structure and menu building
